"""renombrar xp a exp

Revision ID: 73b759e9bba5
Revises: afa27d4386a8
Create Date: 2026-05-14 10:46:04.935466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b759e9bba5'
down_revision: Union[str, Sequence[str], None] = 'afa27d4386a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_exp', sa.Integer(), nullable=False))
    op.drop_column('users', 'total_xp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_xp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'total_exp')
    # ### end Alembic commands ###
